// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Host                                   string
	HostContract                           string
	Language                               string
	VendorAddress                          string
	VendorAddressTranslation               string
	VendorBookingPolicy                    string
	VendorDetail                           string
	VendorLog                              string
	VendorPaymentPolicy                    string
	VendorPaymentPolicyValue               string
	VendorPhone                            string
	VendorRefundAndCancellationPolicy      string
	VendorRefundAndCancellationPolicyValue string
	Vendors                                string
	GooseDBVersion                         string
}{
	Host:                                   "Host",
	HostContract:                           "HostContract",
	Language:                               "Language",
	VendorAddress:                          "VendorAddress",
	VendorAddressTranslation:               "VendorAddressTranslation",
	VendorBookingPolicy:                    "VendorBookingPolicy",
	VendorDetail:                           "VendorDetail",
	VendorLog:                              "VendorLog",
	VendorPaymentPolicy:                    "VendorPaymentPolicy",
	VendorPaymentPolicyValue:               "VendorPaymentPolicyValue",
	VendorPhone:                            "VendorPhone",
	VendorRefundAndCancellationPolicy:      "VendorRefundAndCancellationPolicy",
	VendorRefundAndCancellationPolicyValue: "VendorRefundAndCancellationPolicyValue",
	Vendors:                                "Vendors",
	GooseDBVersion:                         "goose_db_version",
}
