appOptions:
  name: Prime
  serviceName: boilerplate
  deliveryType: http # http, grpc

echoOptions:
  name: boilerplate
  port: 7001
  development: true
  timeout: 30
  basePath: "/api/v1"
  debugHeaders: true
  httpClientDebug: true
  debugErrorsResponse: true
  ignoreLogUrls:
    - "metrics"

grpcOptions:
  name: boilerplate
  port: 7002
  development: true

logOptions:
  level: debug
  logType: 1
  callerEnabled: false

pgOptions:
  driver: postgres
  host: localhost
  port: 5432
  user: local
  password: local
  database: "goose_trial_migrations"
  ssl: disable
  debug: true
  maxOpenConn: 100
  maxIdleConn: 10
  maxLifetimeConn: 2

eventSourceOptions:
  gcpProjectID: "primecrm-dev"
  source: "com.deltahq.sandbox"
  topics:
    cm-topic: "customer"
    hotel-topic: "hotel"
  subscriptions:
    - "sandbox"

grpcClientOptions:
  - name: hotel_service
    port: 7002
    development: true
    host: localhost
  - name: cm_service
    port: 7003
    development: true
    host: localhost
